### ISSUE TITLE
our_map_all.txt

### ISSUE THREAD

**Issue by aniucw** [HuantWang/FUNDED_NISL#21]
our_map_all.txt文件是怎么生成的呢

**Comment by HuantWang** [comment]
Hi, we pre-trained these tokens using the Word2Vec module and then saved the content to a text file.

**Comment by aniucw** [comment]
有没有具体的生成代码或者操作过程呢

**Comment by HuantWang** [comment]
Extract the token dataset by yourself and train the model as shown [here](https://github.com/HuantWang/FUNDED_NISL/blob/5f9ed4dc86eb7c2c532bde37960b2019183affa5/FUNDED/data/data/data_preprocess.py#L66). 
You can also apply state-of-the-art NLP training approaches instead of word2vec, like [BERT](https://github.com/google-research/bert).
