### ISSUE TITLE
Loading pre-trained model weights fails.

### ISSUE THREAD

**Issue by Sillouevan** [HuantWang/FUNDED_NISL#27]
Hello! When I try to follow the command `CUDA_VISIBLE_DEVICES=2 python test.py GGNN GraphBinaryClassification ../data/data/data/cve/badall --storedModel_path "./trained_model/GGNN_GraphBinaryClassification__2023-02-01_05-36-00_f1 = 0.800_best.pkl",` one issue occurred. The details are as follows：
![image](https://github.com/HuantWang/FUNDED_NISL/assets/152054620/a4c0f830-ea93-422b-8c5f-c45506187746)
It mentioned `error! in traububg_utils.py line199`. Does it mean `cli_data_hyperparameter_overrides=args.data_param_override, line 199` in file `training_utils.py`? So how can I solve this problem? And is this the reason why loading pre-trained model weights fails? Looking forward to your reply : ).

**Comment by HuantWang** [comment]
Hi, sorry for the late reply. 
It looks like the issue is due to the model not being loaded correctly [here](https://github.com/HuantWang/FUNDED_NISL/blob/f4d7d9189af4a31c4446df5030ace5b9c167930c/FUNDED/cli_utils/training_utils.py#L194). Could you please provide more detailed information or bug details when executing this function?
